### ISSUE TITLE
chart ancestor does gives an error  (using webtrees 2.0.2)

### ISSUE THREAD

**Issue by hartenthaler** [ric2016/extended_relationships#7]
There is an error in the person part of "charts" "ancestores"; the parts "tree" and "families" are ok. This error occurs for all persons in my tree.
```
Cissee\Webtrees\Module\ExtendedRelationships\ExtendedRelationshipModule …/vendor/aura/router/src/Map.php:152
#0 …/app/Helpers/functions.php(169): Aura\Router\Map->getRoute()
#1 …/app/Module/RelationshipsChartModule.php(189): route()
#2 …/resources/views/lists/individuals-table.phtml(329): Fisharebest\Webtrees\Module\RelationshipsChartModule->chartUrl()
#3 …/app/View.php(186): include('/mnt/web312/a3/...')
```

**Comment by ric2016** [comment]
I can reproduce this - Will be fixed in the next release.

**Comment by ric2016** [comment]
Fixed in the latest release.
